version: "3.8"

services:
  analyser_resume_app:
    container_name: analyser_resume_app
    build: .
    ports:
      - "8501:8501"
    ########################################################## retirar quando levar para produção
    volumes:
      - .:/app  # Ótimo para desenvolvimento; remova para produção
    ############################################################################################# 
    env_file:
      - .env
    restart: always
